# Generated by Django 2.1.7 on 2019-02-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0002_auto_20190215_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
