# Generated by Django 2.1.7 on 2019-02-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0003_relation_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_relations', to='forest.Node'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_relations', to='forest.Node'),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='vote',
            field=models.SmallIntegerField(default=0),
        ),
    ]
