# Generated by Django 2.1.7 on 2019-02-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0005_auto_20190220_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
