# Generated by Django 2.1.7 on 2019-02-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0006_notification_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('create', 'created'), ('delete', 'deleted'), ('modify', 'modified')], default='modify', max_length=100),
        ),
    ]
