# Generated by Django 2.1.7 on 2019-03-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0008_auto_20190315_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
    ]
