# Generated by Django 2.1.7 on 2019-03-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0010_auto_20190318_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='forest.Node'),
        ),
        migrations.AddField(
            model_name='item',
            name='droppable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='max_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='public_can_give',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='public_can_link',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='show_backward_relations',
            field=models.BooleanField(default=True),
        ),
    ]
