# Generated by Django 2.1.7 on 2019-03-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0011_auto_20190318_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
