# Generated by Django 2.1.7 on 2019-03-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0014_auto_20190319_2324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nodeitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='nodeitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='nodeitem',
            name='node',
        ),
        migrations.DeleteModel(
            name='NodeItem',
        ),
    ]
