# Generated by Django 2.1.7 on 2019-03-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0015_auto_20190320_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
